### ISSUE TITLE
Problem with "wait" context 

### ISSUE THREAD

**Issue by nikophil** [Guikingone/panther-extension#11]
version: 0.4.0

```gherkin
Then I wait for "#element" to be visible
```

calls `PantherContext::iWaitForElementToBeVisible()`

which calls `$driver->wait(3000, WebDriverExpectedCondition::visibilityOfAnyElementLocated(WebDriverBy::cssSelector($element)));`

but `PantherDriver::wait()` must be a string...

**Comment by Guikingone** [comment]
Hi 👋 

Thanks for the notice, here's the fix: https://github.com/Guikingone/panther-extension/pull/12
