### ISSUE TITLE
Inconsistencies between DriverInterface and PantherDriver implementation

### ISSUE THREAD

**Issue by nikophil** [Guikingone/panther-extension#7]
Hi,

there are minor inconsistencies between `PantherDriver::wait()` method and its definition in the interface:
- `$timeout` parameter is expected in milliseconds in the phpdoc from the interface althought we're passing it to `$client->wait()` where the parameter is called `timeoutInSecond`
- the phpdoc in the interface expects the `$condition` parameter to be an interger, but the `WebDriverWait::until()` which it is passed expects a callable or a `WebDriverExpectedCondition`. This could be a little bit more annoying because static analysis tools complain about it

For the record, we're using this `wait()` method in order to wait for an element to be visible :
```php
$driver->wait(5, WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::cssSelector($element)));
```

**Comment by Guikingone** [comment]
Hi @nikophil 👋 

Thanks for the issue, this should be fixed in the next PR (planned for 0.4.0) 🙂
